name: marti_case
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Fonts
  google_fonts: ^6.1.0

  bubble: ^1.2.1

  # State Management
  provider: ^6.0.5

  # Page/Screen Navigator
  auto_route: ^10.1.0

  get: ^4.6.1
  get_it: ^8.0.2
  injectable: ^2.3.2
  animations: ^2.0.3
  flutter_background_geolocation: ^4.16.10
  permission_manager:
    git:
      url: "https://github.com/trailon/permission_manager.git"
  flutter_easyloading: ^3.0.5
  dio_cache_interceptor: ^4.0.3
  awesome_dio_interceptor: ^1.1.0
  change_case: ^2.0.1
  change_app_package_name: ^1.4.0
  shadcn_ui: ^0.26.5
  shadcn_flutter: ^0.0.19
  devicelocale: ^0.8.1
  device_preview: ^1.2.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  geocode: ^1.0.3
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generator Starter
  build_runner: ^2.1.5
  # Code Generators
  auto_route_generator: ^10.1.0
  injectable_generator: ^2.4.1

  # Lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
